// <auto-generated />
using System;
using Ccusage.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ccusage.Api.Migrations
{
    [DbContext(typeof(UsageDbContext))]
    [Migration("20260615060724_DiscordSecurityAndMentions")]
    partial class DiscordSecurityAndMentions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ccusage.Api.Data.Entities.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoSyncEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AutoSyncIntervalSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(300);

                    b.Property<string>("ClaudeProjectsPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("DisplayTimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("AppConfigs");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Picture")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubject")
                        .IsUnique()
                        .HasFilter("\"GoogleSubject\" IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("TargetEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("WhenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("WhenUtc");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.IngestedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSyncUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LinesIngested")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("IngestedFiles");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.IngestionSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IngestionSources");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.ModelPricing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CacheReadPerMTok")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("CacheWrite1hPerMTok")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("CacheWrite5mPerMTok")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("InputPerMTok")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<bool>("IsPlaceholder")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelPattern")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("OutputPerMTok")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.HasKey("Id");

                    b.HasIndex("ModelPattern")
                        .IsUnique();

                    b.ToTable("ModelPricings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CacheReadPerMTok = 1.50m,
                            CacheWrite1hPerMTok = 30m,
                            CacheWrite5mPerMTok = 18.75m,
                            DisplayName = "Claude Opus 4.8",
                            InputPerMTok = 15m,
                            IsPlaceholder = false,
                            ModelPattern = "claude-opus-4-8",
                            OutputPerMTok = 75m
                        },
                        new
                        {
                            Id = 2,
                            CacheReadPerMTok = 1.50m,
                            CacheWrite1hPerMTok = 30m,
                            CacheWrite5mPerMTok = 18.75m,
                            DisplayName = "Claude Opus 4.7",
                            InputPerMTok = 15m,
                            IsPlaceholder = false,
                            ModelPattern = "claude-opus-4-7",
                            OutputPerMTok = 75m
                        },
                        new
                        {
                            Id = 3,
                            CacheReadPerMTok = 0.10m,
                            CacheWrite1hPerMTok = 2.00m,
                            CacheWrite5mPerMTok = 1.25m,
                            DisplayName = "Claude Haiku 4.5",
                            InputPerMTok = 1.00m,
                            IsPlaceholder = false,
                            ModelPattern = "claude-haiku-4-5",
                            OutputPerMTok = 5.00m
                        },
                        new
                        {
                            Id = 4,
                            CacheReadPerMTok = 0.30m,
                            CacheWrite1hPerMTok = 6.00m,
                            CacheWrite5mPerMTok = 3.75m,
                            DisplayName = "Claude Fable 5 (placeholder)",
                            InputPerMTok = 3.00m,
                            IsPlaceholder = true,
                            ModelPattern = "claude-fable-5",
                            OutputPerMTok = 15.00m
                        },
                        new
                        {
                            Id = 5,
                            CacheReadPerMTok = 0m,
                            CacheWrite1hPerMTok = 0m,
                            CacheWrite5mPerMTok = 0m,
                            DisplayName = "Unpriced fallback",
                            InputPerMTok = 0m,
                            IsPlaceholder = true,
                            ModelPattern = "*",
                            OutputPerMTok = 0m
                        },
                        new
                        {
                            Id = 6,
                            CacheReadPerMTok = 0.125m,
                            CacheWrite1hPerMTok = 0m,
                            CacheWrite5mPerMTok = 0m,
                            DisplayName = "GPT-5.5 (placeholder)",
                            InputPerMTok = 1.25m,
                            IsPlaceholder = true,
                            ModelPattern = "gpt-5.5",
                            OutputPerMTok = 10.00m
                        },
                        new
                        {
                            Id = 7,
                            CacheReadPerMTok = 0.125m,
                            CacheWrite1hPerMTok = 0m,
                            CacheWrite5mPerMTok = 0m,
                            DisplayName = "GPT-5.4 (placeholder)",
                            InputPerMTok = 1.25m,
                            IsPlaceholder = true,
                            ModelPattern = "gpt-5.4",
                            OutputPerMTok = 10.00m
                        },
                        new
                        {
                            Id = 8,
                            CacheReadPerMTok = 0.05m,
                            CacheWrite1hPerMTok = 0m,
                            CacheWrite5mPerMTok = 0m,
                            DisplayName = "GPT-5.3 Codex (placeholder)",
                            InputPerMTok = 0.50m,
                            IsPlaceholder = true,
                            ModelPattern = "gpt-5.3-codex",
                            OutputPerMTok = 4.00m
                        },
                        new
                        {
                            Id = 9,
                            CacheReadPerMTok = 0.125m,
                            CacheWrite1hPerMTok = 0m,
                            CacheWrite5mPerMTok = 0m,
                            DisplayName = "Other GPT (placeholder)",
                            InputPerMTok = 1.25m,
                            IsPlaceholder = true,
                            ModelPattern = "gpt-",
                            OutputPerMTok = 10.00m
                        });
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.NotificationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DailyDigest")
                        .HasColumnType("boolean");

                    b.Property<int>("DigestHourLocal")
                        .HasColumnType("integer");

                    b.Property<string>("DiscordWebhookUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<long>("LastAuditAlertId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("LastDailySent")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LastThresholdSent")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LastWeeklySent")
                        .HasColumnType("date");

                    b.Property<string>("MentionOnAlert")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("SecurityAlerts")
                        .HasColumnType("boolean");

                    b.Property<bool>("ThresholdEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ThresholdUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("WeeklyDay")
                        .HasColumnType("integer");

                    b.Property<bool>("WeeklyDigest")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("NotificationSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailyDigest = false,
                            DigestHourLocal = 9,
                            Enabled = false,
                            LastAuditAlertId = 0L,
                            SecurityAlerts = false,
                            ThresholdEnabled = false,
                            ThresholdUsd = 0m,
                            WeeklyDay = 1,
                            WeeklyDigest = false
                        });
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FolderName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RepoRoot")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("RepoRoot")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.RequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("QueryString")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text");

                    b.Property<long?>("RequestBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text");

                    b.Property<long?>("ResponseBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("WhenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsDescending();

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.SyncStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("LastDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<int>("LastFilesParsed")
                        .HasColumnType("integer");

                    b.Property<int>("LastFilesScanned")
                        .HasColumnType("integer");

                    b.Property<int>("LastNewRecords")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastSyncUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SyncStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastDurationMs = 0L,
                            LastFilesParsed = 0,
                            LastFilesScanned = 0,
                            LastNewRecords = 0
                        });
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.UsageRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("CacheCreation1hTokens")
                        .HasColumnType("integer");

                    b.Property<int>("CacheCreation5mTokens")
                        .HasColumnType("integer");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("Cwd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("GitBranch")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("IngestedFileId")
                        .HasColumnType("integer");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSidechain")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("claude-code");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DedupKey")
                        .IsUnique();

                    b.HasIndex("IngestedFileId");

                    b.HasIndex("IsSidechain");

                    b.HasIndex("LocalDate");

                    b.HasIndex("Model");

                    b.HasIndex("SessionId");

                    b.HasIndex("Source");

                    b.HasIndex("ProjectId", "LocalDate");

                    b.ToTable("UsageRecords");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Permission")
                        .IsUnique();

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.UsageRecord", b =>
                {
                    b.HasOne("Ccusage.Api.Data.Entities.IngestedFile", "IngestedFile")
                        .WithMany()
                        .HasForeignKey("IngestedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ccusage.Api.Data.Entities.Project", "Project")
                        .WithMany("Records")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestedFile");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.UserPermission", b =>
                {
                    b.HasOne("Ccusage.Api.Data.Entities.AppUser", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.AppUser", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.Project", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
