// <auto-generated />
using System;
using Ccusage.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ccusage.Api.Migrations
{
    [DbContext(typeof(UsageDbContext))]
    partial class UsageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ccusage.Api.Data.Entities.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaudeProjectsPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("DisplayTimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("AppConfigs");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.IngestedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSyncUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LinesIngested")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("IngestedFiles");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.ModelPricing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CacheReadPerMTok")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("CacheWrite1hPerMTok")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("CacheWrite5mPerMTok")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("InputPerMTok")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<bool>("IsPlaceholder")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelPattern")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("OutputPerMTok")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.HasKey("Id");

                    b.HasIndex("ModelPattern")
                        .IsUnique();

                    b.ToTable("ModelPricings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CacheReadPerMTok = 1.50m,
                            CacheWrite1hPerMTok = 30m,
                            CacheWrite5mPerMTok = 18.75m,
                            DisplayName = "Claude Opus 4.8",
                            InputPerMTok = 15m,
                            IsPlaceholder = false,
                            ModelPattern = "claude-opus-4-8",
                            OutputPerMTok = 75m
                        },
                        new
                        {
                            Id = 2,
                            CacheReadPerMTok = 1.50m,
                            CacheWrite1hPerMTok = 30m,
                            CacheWrite5mPerMTok = 18.75m,
                            DisplayName = "Claude Opus 4.7",
                            InputPerMTok = 15m,
                            IsPlaceholder = false,
                            ModelPattern = "claude-opus-4-7",
                            OutputPerMTok = 75m
                        },
                        new
                        {
                            Id = 3,
                            CacheReadPerMTok = 0.10m,
                            CacheWrite1hPerMTok = 2.00m,
                            CacheWrite5mPerMTok = 1.25m,
                            DisplayName = "Claude Haiku 4.5",
                            InputPerMTok = 1.00m,
                            IsPlaceholder = false,
                            ModelPattern = "claude-haiku-4-5",
                            OutputPerMTok = 5.00m
                        },
                        new
                        {
                            Id = 4,
                            CacheReadPerMTok = 0.30m,
                            CacheWrite1hPerMTok = 6.00m,
                            CacheWrite5mPerMTok = 3.75m,
                            DisplayName = "Claude Fable 5 (placeholder)",
                            InputPerMTok = 3.00m,
                            IsPlaceholder = true,
                            ModelPattern = "claude-fable-5",
                            OutputPerMTok = 15.00m
                        },
                        new
                        {
                            Id = 5,
                            CacheReadPerMTok = 0m,
                            CacheWrite1hPerMTok = 0m,
                            CacheWrite5mPerMTok = 0m,
                            DisplayName = "Unpriced fallback",
                            InputPerMTok = 0m,
                            IsPlaceholder = true,
                            ModelPattern = "*",
                            OutputPerMTok = 0m
                        });
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FolderName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RepoRoot")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("RepoRoot")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.UsageRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("CacheCreation1hTokens")
                        .HasColumnType("integer");

                    b.Property<int>("CacheCreation5mTokens")
                        .HasColumnType("integer");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("Cwd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("GitBranch")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("IngestedFileId")
                        .HasColumnType("integer");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSidechain")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DedupKey")
                        .IsUnique();

                    b.HasIndex("IngestedFileId");

                    b.HasIndex("IsSidechain");

                    b.HasIndex("LocalDate");

                    b.HasIndex("Model");

                    b.HasIndex("SessionId");

                    b.HasIndex("ProjectId", "LocalDate");

                    b.ToTable("UsageRecords");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.UsageRecord", b =>
                {
                    b.HasOne("Ccusage.Api.Data.Entities.IngestedFile", "IngestedFile")
                        .WithMany()
                        .HasForeignKey("IngestedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ccusage.Api.Data.Entities.Project", "Project")
                        .WithMany("Records")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestedFile");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Ccusage.Api.Data.Entities.Project", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
